CREATE TABLE IF NOT EXISTS scan_reports (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    scanner_name VARCHAR(255) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    report_text LONGTEXT NOT NULL,
    scanned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
